---
root: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
plugins:
  - "@typescript-eslint"
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:jest/recommended"
  - "plugin:import/recommended"
  - "plugin:import/typescript"
rules:
  "@typescript-eslint/explicit-member-accessibility": error
  "@typescript-eslint/explicit-module-boundary-types": off
  "@typescript-eslint/interface-name-prefix": off
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/camelcase": off
  "@typescript-eslint/no-unused-vars":
    - error
    - ignoreRestSiblings: true
  arrow-spacing:
    - error
  comma-dangle:
    - error
    - always-multiline
  curly:
    - error
  default-case-last: error
  eol-last:
    - error
    - always
  import/first: error
  import/newline-after-import: error
  import/no-unresolved: off
  import/order:
    - error
    - alphabetize:
        order: asc
        caseInsensitive: true
      newlines-between: never
      warnOnUnassignedImports: true
  indent:
    - error
    - 4
    - SwitchCase: 1
      ImportDeclaration: first
  jest/expect-expect: off
  jest/valid-expect: off
  keyword-spacing: error
  linebreak-style:
    - error
    - windows
  max-classes-per-file:
    - error
    - 1
  max-len:
    - error
    - code: 140
  no-console: off
  no-duplicate-imports: error
  no-multi-assign: error
  no-multi-spaces: error
  no-multiple-empty-lines:
    - error
    - max: 1
      maxEOF: 0
  no-restricted-imports: error
  no-return-await: error
  no-trailing-spaces: error
  no-var: error
  object-curly-spacing:
    - error
    - always
  padding-line-between-statements:
    - error 
    - blankLine: always
      prev: "*"
      next: return
  quotes:
    - error
    - double
    - avoidEscape: true
  react/display-name: off
  react/jsx-boolean-value:
    - error
    - never
  react/jsx-indent-props:
    - error
    - 4
  react/jsx-max-props-per-line:
    - 1
    - maximum:
        single: 5
        multi: 1
  react/no-arrow-function-lifecycle: error
  react/prop-types: off
  react/self-closing-comp: error
  require-await: error
  semi:
    - error
    - always
  semi-spacing:
    - error
    - before: false
      after: true
  semi-style:
    - error
    - last
  switch-colon-spacing: error
settings:
  react:
    version: detect
env:
  jest: true
  node: true
